# To be added NGIX for digital ocean: https://realpython.com/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/
version: "3.9"

services:

#    flask:
#        build: .
#        container_name: flask
#        expose:
#          - "5000"
#        working_dir: /app
#        env_file:
#          - .env
#        volumes:
#          - ../instance/:/app/instance/
#
#    nginx:
#        build: ./nginx
#        container_name: nginx
#        ports:
#          - "80:80"
#          - "443:443"
#          - "8443:8443"
#        restart: always
#        volumes:
#          - ./certbot/www/:/var/www/certbot/:ro
#          - ./certbot/conf/:/etc/nginx/ssl/:ro
#
#    certbot:
#        image: certbot/certbot
#        container_name: certbot
#        volumes:
#          - ./certbot/www/:/var/www/certbot/:rw
#          - ./certbot/conf/:/etc/letsencrypt/:rw
#
#    jenkins-blueocean:
#        build: ./jenkins
#        user: root
#        container_name: jenkins-blueocean
#        restart: on-failure
#        expose:
#          - '8080:8080'
#          - '50000:50000'
#        volumes:
#          - 'jenkins-data:/var/jenkins_home'
#          - /var/run/docker.sock:/var/run/docker.sock
#          - ./certbot/www/:/var/www/certbot/:ro
#          - ./certbot/conf/:/etc/nginx/ssl/:ro

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

networks:
  default:
    name: HXBank_bridge

volumes:
  jenkins-data:
  jenkins-docker-certs:
