# To be added NGIX for digital ocean: https://realpython.com/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/
version: "3.9"

services:

  flask:
    build: .
    container_name: flask
    expose:
      - "5000"
    working_dir: /app
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

  jenkins-docker:
    container_name: jenkins-docker
    privileged: true
    network_mode: jenkins
    environment:
        - DOCKER_TLS_CERTDIR=/certs
    volumes:
        - 'jenkins-docker-certs:/certs/client'
        - 'jenkins-data:/var/jenkins_home'
    ports:
        - '2376:2376'
    image: 'docker:dind'

  myjenkins-blueocean:
    build: ./jenkins
    container_name: jenkins-blueocean
    restart: on-failure
    network_mode: jenkins
    environment:
        - 'DOCKER_HOST=tcp://docker:2376'
        - 'DOCKER_CERT_PATH=/certs/client'
        - 'DOCKER_TLS_VERIFY=1'
    ports:
        - '8080:8080'
        - '50000:50000'
    volumes:
        - 'jenkins-data:/var/jenkins_home'
        - 'jenkins-docker-certs:/certs/client:ro'

networks:
  default:
    name: HXBank_bridge