# To be added NGIX for digital ocean: https://realpython.com/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/
version: "3.9"

services:

  flask:
    build: .
    container_name: flask
    expose:
      - "5000"
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./instance/database.db:/app/webportal/instance/database.db

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    restart: always
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  jenkins:
    container_name: jenkins
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - 'jenkins-docker-certs:/certs/client'
      - 'jenkins-data:/var/jenkins_home'
    expose:
      - '2376:2376'
    image: 'docker:dind'

  jenkins-blueocean:
    build: ./jenkins
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      - 'DOCKER_HOST=tcp://docker:2376'
      - 'DOCKER_CERT_PATH=/certs/client'
      - 'DOCKER_TLS_VERIFY=1'
    expose:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins-data:/var/jenkins_home'
      - 'jenkins-docker-certs:/certs/client:ro'
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
networks:
  default:
    name: HXBank_bridge

volumes:
  jenkins-data:
  jenkins-docker-certs:
