version: "3.9"

services:

  db:
    image: mysql:latest
    container_name: db
    env_file:
      - mysql.env
    restart: always
    ports:
      - '3306:3306'

networks:
  default:
    driver: bridge
    name: HXBank_bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
