# To be added NGIX for digital ocean: https://realpython.com/dockerizing-flask-with-compose-and-machine-from-localhost-to-the-cloud/
version: "3.9"

services:

  flask:
    build: .
    container_name: flask
    expose:
      - "5000"
    working_dir: /app
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always